version: "3"
services:
  metabase:
    image: metabase/metabase:v0.51.9.4
    hostname: metabase
    volumes:
      - $FENRIR_ROOT_DIR/analytics/volumes/metabase/data/:/metadata.db/
      - /dev/urandom:/dev/random:ro
    ports:
      - target: 3000
        published: 10031
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.analytics == true
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 5s
    healthcheck:
      test: ["curl", "--fail",  "-I", "http://localhost:3000/api/health || exit 1"]
      interval: 100s
      timeout: 100s
      retries: 5
    networks:
      - internal_network

networks:
  internal_network:
    name: $FENRIR_DOCKER_NETWORK
    driver: overlay
    attachable: true
    external: true
