version: "3"
services:
  metabase:
    image: metabase/metabase:v0.52.4
    hostname: metabase
    volumes:
      - $FENRIR_ROOT_DIR/analytics/volumes/metabase/data/:/metabase-data/
      - /dev/urandom:/dev/random:ro
    ports:
      - target: 3000
        published: 10031
        mode: host
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
      MB_DB_FILE: /metabase-data/metabase.db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.analytics == true
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
        window: 120s
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 5s
#    healthcheck:
#      test: ["CMD-SHELL", "curl -s 'http://127.0.0.1:3000/api/health' | grep '{\"status\":\"ok\"}'; do sleep 1; done"]
#      interval: 100s
#      timeout: 10s
#      retries: 5
    networks:
      - internal_network

networks:
  internal_network:
    name: $FENRIR_DOCKER_NETWORK
    driver: overlay
    attachable: true
    external: true
