kafka-stack:
  range: 10000-10029
  services:
    - zookeeper:
      - target: 2181
        published: 10000
        mode: host
  - zoonavigator:
      - target: 8000
        published: 10001
        mode: host
  - kafka:
      internally_exposed:
        10003:"INTERNAL (19092 before)"
      externally_exposed:
      - target: 9092
        published: 9092
        mode: host
      - target: 29092
        published: 10004
        mode: host
      - target: 9999
        published: 10005
        mode: host
  - schema-registry:
      - target: 8081
        published: 10006
        mode: host
  - rest-proxy:
      - target: 8082
        published: 10007
        mode: host
  - kafka-connect:
      - target: 8083
        published: 10008
        mode: host
  - kafdrop:
      - target: 9000
        published: 10009
        mode: host
  - ksqldb:
      - target: 8088
        published: 10010
        mode: host
  - kafka-ui:
      - target: 8080
        published: 10011
        mode: host

analytics-stack: 10030-10059

  - postgres:
      - target: 5432
        published: 10030
        mode: host
  - metabase:
      - target: 3000
        published: 10031
        mode: host


processing-stack: 10060 - 10079
  - spark:
      - target: 8080
        published: 10060
        mode: host
      - target: 7077
        published: 10061
        mode: host
  - spark-driver:
      - target: 4040
        published: 10062
        mode: host
      - target: 18080
        published: 10063
        mode: host
  - spark-worker1:
      - target: 8081
        published: 10064
        mode: host
  - flink-jobmanager:
      - target: 8081
        published: 10065
        mode: host
      - target: 6123
        published: 10066
        mode: host
      - target: 6124
        published: 10067
        mode: host
  - flink-taskmanager:
      - target:
        published
        


orchestration-stack: 10080 - 10099

  # airflow
  - webserver:
      - target: 8080
        published: 10080
        mode: host


portainer-stack: 10100 - 10110

  portainer:
    - target: 9443
      published: 10100
      mode: host
    - target: 8000
      published: 10101
      mode: host
    - target: 9000
      published: 10102
      mode: host

custom: 20000 >
  - kstream:
      - target: 8000
        published: 20000
        mode: host
  - confluent-fenrir-kafka:
      - target: 22
        published: 20022
        mode: host
