version: '3'

services:
  agent:
    image: portainer/agent:2.21.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - internal_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.21.4
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - ~/.fenrir/portainer/volumes/data:/data
    ports:
      - target: 9443
        published: 10060
        mode: host
      - target: 8000
        published: 10061
        mode: host
      - target: 9000
        published: 10062
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - internal_network

networks:
  internal_network:
    name: ${FENRIR_DOCKER_NETWORK}
    driver: overlay
    attachable: true
    external: true

volumes:
  portainer_data:
